// Port of :core gloss/: Gloss model, prompts (from fixtures/prompts.json, generated by Kotlin), lenient JSON
// extraction, response parsing, clitic helpers, pre-gloss planning.
import prompts from '../../../fixtures/prompts.json' with { type: 'json' };
import { formKey } from './hash.ts';
import { type Page, type Token, type TokenizedText } from './text.ts';
import { Status } from './vocab.ts';

export interface VerbForm {
  infinitive: string; tense?: string | null; mood?: string | null; person?: string | null; number?: string | null;
  formation?: string | null; whyThisForm?: string | null;
}
export interface Clitic { pronoun: string; role: string; refersTo?: string | null; note?: string | null }
export interface Gloss {
  form: string; lemma: string; partOfSpeech: string; meaningInContext: string;
  grammarNote?: string | null; otherMeanings?: string[]; isIdiomOrPhrase?: boolean; phrase?: string | null;
  phraseMeaning?: string | null; verb?: VerbForm | null; clitics?: Clitic[]; roots?: string | null;
}
export interface FoundPhrase { phrase: string; meaning: string }
export interface SentenceAnalysis { translation: string | null; phrases: FoundPhrase[] }
export interface GlossRequest { id: string; form: string; sentence: string; previous?: Gloss }

export const GLOSS_SYSTEM: string = prompts.glossSystem;
export const SENTENCE_SYSTEM: string = prompts.sentenceSystem;

const reminder = (isRetry: boolean) => (isRetry ? '\nYour previous reply could not be parsed. Reply with valid JSON only.' : '');

/** The previous answer as Kotlin serializes it (declaration order; nulls and defaults omitted). */
function previousJson(g: Gloss): Record<string, unknown> {
  const o: Record<string, unknown> = { form: g.form, lemma: g.lemma, partOfSpeech: g.partOfSpeech, meaningInContext: g.meaningInContext };
  if (g.grammarNote != null) o.grammarNote = g.grammarNote;
  if (g.otherMeanings && g.otherMeanings.length) o.otherMeanings = g.otherMeanings;
  if (g.isIdiomOrPhrase) o.isIdiomOrPhrase = true;
  if (g.phrase != null) o.phrase = g.phrase;
  if (g.phraseMeaning != null) o.phraseMeaning = g.phraseMeaning;
  if (g.verb != null) o.verb = g.verb;
  if (g.clitics && g.clitics.length) o.clitics = g.clitics;
  if (g.roots != null) o.roots = g.roots;
  return o;
}

export function glossUserPrompt(requests: GlossRequest[], isRetry = false): string {
  const items = requests.map((r) => {
    const o: Record<string, unknown> = { id: r.id, form: r.form, sentence: r.sentence };
    if (r.previous) o.previousAnswer = previousJson(r.previous);
    return o;
  });
  const improve = requests.some((r) => r.previous) ? prompts.improveNote : '';
  return 'Gloss these items:\n' + JSON.stringify({ items }) + improve + reminder(isRetry);
}

export function sentenceUserPrompt(sentences: Array<[string, string]>, isRetry = false): string {
  const items = sentences.map(([id, sentence]) => ({ id, sentence }));
  return 'Translate these sentences and find their expressions:\n' + JSON.stringify({ sentences: items }) + reminder(isRetry);
}

// --- JsonExtractor.kt ---

function lenientParse(s: string): unknown {
  try {
    return JSON.parse(s);
  } catch {
    try {
      return JSON.parse(s.replace(/,\s*([}\]])/g, '$1')); // trailing commas
    } catch {
      return undefined;
    }
  }
}

function matchingEnd(text: string, start: number): number {
  let depth = 0, inString = false, escaped = false;
  for (let i = start; i < text.length; i++) {
    const c = text[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (c === '\\') escaped = true;
      else if (c === '"') inString = false;
      continue;
    }
    if (c === '"') inString = true;
    else if (c === '{' || c === '[') depth++;
    else if (c === '}' || c === ']') {
      depth--;
      if (depth === 0) return i;
      if (depth < 0) return -1;
    }
  }
  return -1;
}

function* scan(text: string): Generator<unknown> {
  let i = 0;
  while (i < text.length) {
    const c = text[i];
    if (c === '{' || c === '[') {
      const end = matchingEnd(text, i);
      if (end > 0) {
        const parsed = lenientParse(text.slice(i, end + 1));
        if (parsed !== undefined) {
          yield parsed;
          i = end + 1;
          continue;
        }
      }
    }
    i++;
  }
}

/** Every parseable top-level JSON value in [text], fenced code blocks first. */
export function* jsonCandidates(text: string): Generator<unknown> {
  for (const m of text.matchAll(/```(?:json|JSON)?\s*\n?([\s\S]*?)```/g)) yield* scan(m[1]);
  yield* scan(text);
}

export class MalformedResponse extends Error {}

const LIST_KEYS = ['glosses', 'items', 'results', 'words'];
const isObj = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null && !Array.isArray(v);
const str = (v: unknown) => (typeof v === 'string' ? v : null);
const nonBlank = (v: unknown) => (typeof v === 'string' && v.trim() ? v : null);

function itemsOf(v: unknown): Record<string, unknown>[] {
  if (Array.isArray(v)) return v.filter(isObj);
  if (isObj(v)) {
    for (const k of LIST_KEYS) if (Array.isArray(v[k])) return (v[k] as unknown[]).filter(isObj);
    if ('meaningInContext' in v || 'meaning_in_context' in v) return [v];
  }
  return [];
}

function pick(o: Record<string, unknown>, ...names: string[]): unknown {
  for (const n of names) if (o[n] !== undefined) return o[n];
  return undefined;
}

function decodeVerb(v: unknown): VerbForm | null {
  if (!isObj(v) || !nonBlank(v.infinitive)) return null;
  return {
    infinitive: v.infinitive as string, tense: str(v.tense), mood: str(v.mood), person: str(v.person), number: str(v.number),
    formation: str(pick(v, 'formation', 'how_formed', 'howFormed')), whyThisForm: str(pick(v, 'whyThisForm', 'why_this_form', 'why', 'reason')),
  };
}

function decodeGloss(o: Record<string, unknown>, request: GlossRequest): Gloss | null {
  const meaning = nonBlank(pick(o, 'meaningInContext', 'meaning_in_context', 'meaning'));
  if (!meaning) return null;
  const clitics = Array.isArray(o.clitics)
    ? o.clitics.filter(isObj).filter((c) => nonBlank(c.pronoun) && typeof c.role === 'string').map((c) => ({
      pronoun: c.pronoun as string, role: c.role as string, refersTo: str(pick(c, 'refersTo', 'refers_to')), note: str(c.note),
    }))
    : [];
  const other = pick(o, 'otherMeanings', 'other_meanings');
  return {
    form: nonBlank(o.form) ?? request.form,
    lemma: nonBlank(o.lemma) ?? request.form,
    partOfSpeech: str(pick(o, 'partOfSpeech', 'part_of_speech', 'pos')) ?? '',
    meaningInContext: meaning,
    grammarNote: nonBlank(pick(o, 'grammarNote', 'grammar_note')),
    otherMeanings: Array.isArray(other) ? other.filter((x): x is string => typeof x === 'string' && x.trim() !== '') : [],
    isIdiomOrPhrase: pick(o, 'isIdiomOrPhrase', 'is_idiom_or_phrase') === true,
    phrase: nonBlank(o.phrase),
    phraseMeaning: nonBlank(pick(o, 'phraseMeaning', 'phrase_meaning')),
    verb: decodeVerb(o.verb),
    clitics,
    roots: nonBlank(o.roots),
  };
}

/** Valid glosses for [requests] by id; throws MalformedResponse if the text has no usable JSON. */
export function parseGlosses(text: string, requests: GlossRequest[]): Map<string, Gloss> {
  let items: Record<string, unknown>[] | null = null;
  for (const c of jsonCandidates(text)) {
    const list = itemsOf(c);
    if (list.length) { items = list; break; }
  }
  if (!items) throw new MalformedResponse('No gloss JSON found in model output: ' + text.slice(0, 200));
  const byId = new Map(requests.map((r) => [r.id, r]));
  const unmatched = [...requests];
  const out = new Map<string, Gloss>();
  for (const o of items) {
    const id = typeof o.id === 'string' ? o.id : typeof o.id === 'number' ? String(o.id) : null;
    let req = id !== null ? byId.get(id) : undefined;
    if (req && !unmatched.includes(req)) req = undefined;
    if (!req && typeof o.form === 'string') {
      const same = unmatched.filter((r) => r.form.toLowerCase() === (o.form as string).toLowerCase());
      if (same.length === 1) req = same[0];
    }
    if (!req && id === null && unmatched.length === 1) req = unmatched[0];
    if (!req) continue;
    const g = decodeGloss(o, req);
    if (!g) continue;
    out.set(req.id, g);
    unmatched.splice(unmatched.indexOf(req), 1);
  }
  return out;
}

export function parseSentences(text: string, ids: string[]): Map<string, SentenceAnalysis> {
  let entries: Record<string, unknown>[] | null = null;
  for (const c of jsonCandidates(text)) {
    const list = isObj(c) ? (c.sentences ?? c.items ?? c.results) : c;
    if (Array.isArray(list)) {
      const objs = list.filter(isObj);
      if (objs.length) { entries = objs; break; }
    }
  }
  if (!entries) throw new MalformedResponse('No sentence JSON found in model output: ' + text.slice(0, 200));
  const out = new Map<string, SentenceAnalysis>();
  const remaining = [...ids];
  entries.forEach((e, i) => {
    const rawId = typeof e.id === 'string' ? e.id : typeof e.id === 'number' ? String(e.id) : null;
    const id = rawId !== null && remaining.includes(rawId) ? rawId : (rawId === null && remaining.includes(ids[i]) ? ids[i] : null);
    if (id === null) return;
    const phrases = (Array.isArray(e.phrases) ? e.phrases : []).filter(isObj).flatMap((p) => {
      const phrase = typeof p.phrase === 'string' ? p.phrase.trim() : '';
      return phrase && phrase.includes(' ') ? [{ phrase, meaning: typeof p.meaning === 'string' ? p.meaning.trim() : '' }] : [];
    });
    out.set(id, { translation: nonBlank(e.translation)?.trim() ?? null, phrases });
    remaining.splice(remaining.indexOf(id), 1);
  });
  return out;
}

// --- Clitics ---

export type CliticRole = 'DIRECT_OBJECT' | 'INDIRECT_OBJECT' | 'REFLEXIVE' | 'RECIPROCAL' | 'PRONOMINAL' | 'ACCIDENTAL_SE' | 'IMPERSONAL_SE' | 'OTHER';
export const CLITIC_LABEL: Record<CliticRole, string> = {
  DIRECT_OBJECT: 'direct object', INDIRECT_OBJECT: 'indirect object', REFLEXIVE: 'reflexive', RECIPROCAL: 'reciprocal',
  PRONOMINAL: 'pronominal verb', ACCIDENTAL_SE: 'accidental se', IMPERSONAL_SE: 'impersonal / passive se', OTHER: 'other',
};

export function cliticRole(role: string): CliticRole {
  const r = role.toLowerCase();
  if (r.includes('indirect') || r === 'io' || r.includes('dative')) return 'INDIRECT_OBJECT';
  if (r.includes('direct') || r === 'do' || r.includes('accusative')) return 'DIRECT_OBJECT';
  if (r.includes('reciproc')) return 'RECIPROCAL';
  if (r.includes('reflex')) return 'REFLEXIVE';
  if (['accident', 'no-fault', 'involuntary', 'unplanned'].some((k) => r.includes(k))) return 'ACCIDENTAL_SE';
  if (r.includes('impersonal') || r.includes('passive')) return 'IMPERSONAL_SE';
  if (['pronominal', 'inherent', 'lexical'].some((k) => r.includes(k))) return 'PRONOMINAL';
  return 'OTHER';
}

const PRONOUNS = new Set(['me', 'te', 'se', 'lo', 'la', 'le', 'nos', 'os', 'los', 'las', 'les']);
const SHORT_IMPERATIVES = new Set(['di', 'haz', 'pon', 'ven', 'ten', 'sal', 've', 'sé', 'da', 'vamo']);

/** Pronouns glued onto the end of a verb form: "observándome" → base "observándo" + ["me"]. */
export function splitClitics(form: string, clitics: Clitic[]): { base: string; attached: string[] } {
  const wanted = clitics.map((c) => c.pronoun.toLowerCase().trim()).filter((p) => PRONOUNS.has(p));
  let base = form;
  const attached: string[] = [];
  for (;;) {
    const lower = base.toLowerCase();
    const p = [...wanted].sort((a, b) => b.length - a.length).find((x) => lower.endsWith(x) && base.length - x.length >= 2);
    if (!p) break;
    attached.unshift(base.slice(base.length - p.length));
    base = base.slice(0, base.length - p.length);
    wanted.splice(wanted.indexOf(p), 1);
  }
  if (attached.length === 0) return { base: form, attached: [] };
  const nfd = base.toLowerCase().normalize('NFD');
  const plain = nfd.replace(/\p{M}/gu, '');
  const host = plain.endsWith('r') || plain.endsWith('ndo') || nfd !== plain || SHORT_IMPERATIVES.has(plain) || attached.length >= 2;
  return host ? { base, attached } : { base: form, attached: [] };
}

export function verbSummary(v: VerbForm): string {
  const tm = [v.tense, v.mood].filter((x) => x && x.trim()).join(' ');
  const person = v.person ? (/person|usted|vos/i.test(v.person) ? v.person : `${v.person} person`) : null;
  const pn = [person, v.number].filter((x) => x && x.trim()).join(' ');
  return [tm, pn].filter((x) => x).join(' · ');
}

/** True for glosses saved before detailed explanations existed. */
export const lacksDetail = (g: Gloss) => !g.roots && !g.verb && !(g.clitics && g.clitics.length) && /verb/i.test(g.partOfSpeech);

// --- PreGlossPlanner.kt ---

/** One request per distinct (form, sentence) for words not KNOWN/IGNORED, at most [maxPerForm] sentences each. */
export async function planPreGloss(
  text: TokenizedText, statuses: Map<string, number>, maxPerForm: number, tokens: Token[], hash: (s: string) => Promise<string>,
): Promise<GlossRequest[]> {
  const perForm = new Map<string, Set<string>>();
  const out: GlossRequest[] = [];
  for (const t of tokens) {
    const form = t.normalized;
    if (!form) continue;
    const s = statuses.get(form) ?? Status.NEW;
    if (s === Status.KNOWN || s === Status.IGNORED) continue;
    let set = perForm.get(form);
    if (!set) perForm.set(form, (set = new Set()));
    if (set.size >= maxPerForm) continue;
    const sentence = text.sentenceFor(t);
    const h = await hash(sentence);
    if (!set.has(h)) {
      set.add(h);
      out.push({ form: t.text, sentence, id: `${form}#${out.length}` });
    }
  }
  return out;
}

/** Tokens of [count] pages from [fromPage] (clamped); count <= 0 means to the end. */
export function pageWindow(pages: Page[], fromPage: number, count: number): Token[] {
  if (pages.length === 0) return [];
  const from = Math.max(0, Math.min(fromPage, pages.length - 1));
  const to = count <= 0 ? pages.length : Math.min(from + count, pages.length);
  return pages.slice(from, to).flatMap((p) => p.tokens);
}

export { formKey };
