// The TypeScript port must reproduce :core exactly on the fixtures generated by Kotlin (GoldenFixtureTest).
import assert from 'node:assert/strict';
import { test } from 'node:test';
import golden from '../../fixtures/text-golden.json' with { type: 'json' };
import prompts from '../../fixtures/prompts.json' with { type: 'json' };
import { formKey, sentenceHash } from '../src/core/hash.ts';
import { glossUserPrompt, pageWindow, planPreGloss, sentenceUserPrompt } from '../src/core/gloss.ts';
import { cleanImport, locatePhrase, paginate, suggestTitle, tokenize } from '../src/core/text.ts';
import { Status } from '../src/core/vocab.ts';

for (const [n, t] of golden.texts.entries()) {
  test(`text ${n}: tokens, sentences, hashes, pages, cleanup, plan`, async () => {
    const tt = tokenize(t.source);
    assert.deepEqual(tt.tokens.map((k) => [k.text, k.kind, k.normalized, k.sentenceIndex]), t.tokens);
    const sentences = [];
    for (let i = 0; i < tt.sentenceCount; i++) sentences.push([tt.sentenceText(i), await sentenceHash(tt.sentenceText(i))]);
    assert.deepEqual(sentences, t.sentences);
    assert.deepEqual(paginate(tt, 6).map((p) => [p.tokens[0].index, p.tokens[p.tokens.length - 1].index]), t.pages6);
    assert.equal(cleanImport(t.source), t.cleaned);
    assert.equal(cleanImport(t.source, false), t.cleanedNoJoin);
    assert.equal(suggestTitle(t.source), t.title);
    const statuses = new Map([['el', Status.KNOWN], ['la', Status.IGNORED]]);
    const plan = await planPreGloss(tt, statuses, 2, pageWindow(paginate(tt), 0, 0), sentenceHash);
    assert.deepEqual(plan.map((r) => [r.form, r.sentence]), t.plan);
  });
}

test('form keys', () => {
  for (const [w, k] of golden.formKeys) assert.equal(formKey(w), k, w);
});

test('phrase location', () => {
  for (const c of golden.phraseLocate) {
    const hit = locatePhrase(tokenize(c.sentence).tokens, c.phrase);
    assert.deepEqual(hit ? hit.map((t) => t.index) : null, c.tokenIndices, c.phrase);
  }
});

test('prompts are byte-identical to Android', () => {
  assert.equal(glossUserPrompt([
    { form: 'banco', sentence: 'Me senté en el banco.', id: '1' },
    { form: 'dáselo', sentence: 'Dáselo "ya".', id: '2' },
  ]), prompts.sampleUser);
  assert.equal(glossUserPrompt([{
    form: 'banco', sentence: 'Me senté en el banco.', id: '1',
    previous: { form: 'banco', lemma: 'banco', partOfSpeech: 'noun', meaningInContext: 'bank' },
  }], true), prompts.sampleUserImprove);
  assert.equal(sentenceUserPrompt([['0', 'Hola.'], ['1', '¿Qué tal?']]), prompts.sampleSentenceUser);
});
